# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: load_test
  host: localhost
  username: root
  password: ''

production:
  <<: *default
  database: <%= ENV.fetch("RAILS_DATABASE_NAME") { '' } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { '' } %>
  username: <%= ENV.fetch("RAILS_DATABASE_USERNAME") { '' } %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { '' } %> 
